### ISSUE TITLE
Publish latest version to NPM registry

### ISSUE THREAD

**Issue by pepijnverburg** [davidyaha/graphql-mqtt-subscriptions#9]
Hi all,

Thanks for this package; helps a lot in bootstrapping some of the MQTT to GraphQL linking and still works fine with the current graphql-subscriptions implementation. However, I noticed that the one published on NPM is still an old version?

Is it possible to publish the latest version? Especially the wildcard functionality is powerful to use.

Thanks in advance!

**Comment by davidyaha** [comment]
Hey @pepijnverburg! Thanks for letting me know and sorry for that! 
Must have been a slip up on my part.
I will try to get to it today.

**Comment by pepijnverburg** [comment]
Hi David! Thanks for the quick reply, let me know when you have found the time to publish it. Best of luck!

**Comment by shantanoo-desai** [comment]
👍 I am really waiting for the wildcard functionality too!

@davidyaha  I am trying to subscribe to a topic (`test/+/env`) but I never get a response. I have to subscribe to topics individually like `test/1/env` etc. 

Is there a way around this?

**Comment by davidyaha** [comment]
Just published version graphql-mqtt-subscriptions@1.2.0
@pepijnverburg @shantanoo-desai  Let me know if all goes well!

Again, sorry for the delay!

**Comment by pepijnverburg** [comment]
Just briefly tested and all looks good, wildcards working properly! Thanks again for the quick update, closing this issue.
